version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: covidapp
    ports:
      - "5050:80"
    links:
      - mysql:db
    volumes:
      - .:/app
  mysql:
    image: mysql
    env_file:
      - docker-compose.env
    volumes:
      - ./mysqldata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "5051:80"
    links:
      - mysql:db

  composer:
    image: composer
    volumes:
      - .:/app
    command:
      - install